dist: trusty
sudo: required
language: node_js
node_js:
  - "6.11.3"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - "npm test"

addons:
  sonarcloud:
    organization: "sgt-fields"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'